### ISSUE TITLE
Problem with scroll to bottom

### ISSUE THREAD

**Issue by AymericM10** [IchiiDev/profile#1]
Can't scroll to bottom on mobile, tested on iOS 14.4

**Comment by AymericM10** [comment]
Not working on computer, tested on Windows 10 with Brave.

**Comment by IchiiDev** [comment]
This is a known issue, will be fixed soon.

**Comment by IchiiDev** [comment]
Can you explain the step you made to reproduce the bug on your WebBrowser ? So I can understand where the issue is

**Comment by AymericM10** [comment]
To reproduce bug, you have to add several lines in your list of projects. Try with 10 lines.
I've used your project for my website and I have fixed that with the "overflow" in CSS.

**Comment by IchiiDev** [comment]
Yup I know the issue with overflow and it will be enabled on mobile but note that for design issues, the overflow on computer will not be enabled, I will try to add an internal scroll bar to the projects panel soon to fix this issue.

**Comment by AymericM10** [comment]
I don't have repository for the moment, so you can check here : [unicorn-network.xyz](https://unicorn-network.xyz)

**Comment by IchiiDev** [comment]
It's fixed on mobile, still I do not recommend adding too much project ATM as this is breaking the webpage on computer.
You can hot fix this issue by removing the CSS rule in `assets/style.css` line 19

```css
html, body { 
  box-sizing: border-box;
  padding: 0;
  margin: 0;
  height: 100%;

  background-color: #333;
  overflow: hidden; /* Remove this line */
}
```
But this change will not be implemented in production code since there is a way to keep the no global scroll design.
