### ISSUE TITLE
CSS Optimization

### ISSUE THREAD

**Issue by Hugoto69** [IchiiDev/profile#4]
# CSS Optimization

## Unit of measure "px" is redundant
```css
.projects > .project-box:hover {
    box-shadow: 0 0 7px 3px rgba(0,0,0,0.75);
    transition: box-shadow 0.1s;
}
```
## Properties may be safely replaced with 'margin' shorthand
```css
.profile { 
  background-color: #2C2F33;
  width: 600px;
    margin: 10% auto 50px;
    border-radius: 20px;
  display: grid;
  grid-template-rows: auto 1fr auto;
  min-height: 400px;
  padding: 0;
}
```
## Properties may be safely replaced with 'padding' shorthand
```css
.projects > .project-box {
    box-shadow: none;
    transition: box-shadow 0.1s;
    display: flex;
    margin-top: 10px;
    margin-bottom: 10px;
    padding: 5px 5px 5px 10px;
}
```
## Properties may be safely replaced with 'margin' shorthand
```css
@media (max-width: 600px) { 

    body {
        overflow-y: scroll !important;
    }

    .box.profile {
        width: 100%;
        height: 100%;
        margin: 0;
    }

    .top-part { border-radius: 0; }
    .bottom-part { border-radius: 0; }
 }
```
